export const MIN_GUILD_RAID_REPORTS_FOR_CHARACTER_ELIGIBILITY = 2;
export const MIN_CHARACTER_RAID_PULLS_FOR_RANKING_ELIGIBILITY = 50;
export const MIN_CHARACTER_RAID_MYTHIC_REPORTS_FOR_CCG_ELIGIBILITY = 2;
